#define IDI_BITMAP_IMG 700
/*
#define IDI_ICON 303
#define IDC_CURSOR 667
*/
#ifndef RESOURCE_H_INCLUDED
#define RESOURCE_H_INCLUDED
#define IDD_CONTROLS_DLG  101
#define IDC_CLOSE_BTN     1000
#endif

